### ISSUE TITLE
Detalhes importantes

### ISSUE THREAD

**Issue by davidsdearaujo** [leeashley/atelo_desktop#1]
Olá, gostei bastante da iniciativa!

Gostaria de contribuir, mas preciso saber de alguns detalhes para conseguir rodar o projeto:
 - Versão do Flutter utilizada no projeto;
 - Qual método está utilizando para gerar a build para Windows;

Acredito que seja importante que esses detalhes estejam explícitos no `README.md`, para facilitar a contribuição de outros devs

**Comment by leeashley** [comment]
Olá @davidsdearaujo, muito obrigado pelo feedback.
Acabei de atualizar o arquivo readme do projeto, as informações adicionadas devem sanar essa questão citada por você. Sinceramente não esperava que o projeto fosse chamar tanta atenção assim.

OBS: No Windows, atualmente existe um problema de exibir o terminal ao executar/criar um processo a partir do process.run do Dart. Existe um problema aberto no github oficial do Flutter sobre o assunto, no projeto do Atelo foi aplicado uma solução citada nos comentários, segue o link:

https://github.com/dart-lang/sdk/issues/39945

Qualquer coisa é só falar, obrigado mais uma vez.
Caso o seu comentário seja positivo, ou não tenha mais comentários sobre o build e versão do flutter do projeto, fecharei esse problema.
